<a href="https://colab.research.google.com/github/sumankmaiti/All-in-one/blob/main/NeuralNetworkWithMultipleLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import  *

# taking training set with 3 features and 8 samples
training_inputs = array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
print("training input:\n", training_inputs)
print("with {} features and {} sampels.".format(training_inputs.shape[1], training_inputs.shape[0]))

# output of data
training_outputs = array([[0], [1], [1], [1], [0], [0], [1], [0]])
print("training output:\n", training_outputs)

# we create 1 hidden layer with 3 neurons
no_of_nurons = 3

# each neuron will take 3 inputs.
each_nurons_input = training_inputs.shape[1]

# weights matrix for inputs. the input data has 3 features and there are 3 neurons so, 3x3 matrix will needed.
# random weight will be generated
weights_for_input_nurons = random.uniform(size=(each_nurons_input, no_of_nurons))

# for 3 neurons only 3 bias value needed. so, 1x3 matrix needed with random value
bias_for_input_nurons = random.uniform(size=(1, no_of_nurons))

# printing weight matrix and bias matrix
print("weight matrix of 3 neurons:\n", weights_for_input_nurons)
print("bias matrix of 3 neurons:\n", bias_for_input_nurons)

# one output layer needed
output_nuron = 1

# 1 output layer has 3 inputs from 3 outputs.
# so, 3x1 matrix needed for weight and 1 bias value needed for output neuron
weights_for_output_nurons = random.uniform(size=(no_of_nurons, output_nuron))
bias_for_output_nurons = random.uniform(size=(1, output_nuron))

# printing weight matrix and bias matrix of output neuron
print("weight matrix of output neuron:\n", weights_for_output_nurons)
print("bias matrix of output neuron:\n", bias_for_output_nurons)

# learning rate
lr = 0.1


# to calculate the sigmoid of the given input
def sigmoid(x):
    return 1/(1 + exp(-x))


# to calculate derivative for gradient decent
def derivative(x):
    return x * (1 - x)


# perform 10000 iteration for learning
for iteration in range(10000):

  # forward propagation
    input = training_inputs  # training data 8x3

    # inputs of 3 neurons. each columns of weight_for_input_nurons represents weights for 3 neurons.
    #      8x3                   8x3             3x3                      1x3
    input_of_input_nurons = dot(input, weights_for_input_nurons) + bias_for_input_nurons

    # perform sigmoid function to get the prediction of the 3 neurons
    #    8x3                                8x3
    output_of_input_nurons = sigmoid(input_of_input_nurons)

    # the output of the three neurons will be input of the output neuron.
    #       8x1                         8x3                      3x1                         1x1
    input_of_output_nuron = dot(output_of_input_nurons, weights_for_output_nurons) + bias_for_output_nurons

    # final prediction from output neuron
    # 8x1                   8x1
    output = sigmoid(input_of_output_nuron)

  # back propagation
    # difference from original output
    #  8x1              8x1            8x1
    output_error = training_outputs - output

    # performing derivative of output of output neuron
    #      8x1                         8x1
    derivative_of_output = derivative(output)

    # performing derivative of output of intermediate 3 neurons
    #      8x3                                     8x3
    derivative_of_input_nurons = derivative(output_of_input_nurons)

    # multiplying error with derivative
    #      8x1             8x1               8x1
    delta_of_output = output_error * derivative_of_output

    # error matrix for 3 internal neurons
    #     8x3                     8x1                T(3x1) = 1x3
    input_nuron_error = dot(delta_of_output, weights_for_output_nurons.T)

    # multiplying error with derivative
    #        8x3                      8x3                      8x3
    delta_of_input_nurons = derivative_of_input_nurons * input_nuron_error

    # getting new weight for output neuron
    #  3x1                T(8x3) = 3x8                    8x1
    new_weight_output = dot(output_of_input_nurons.T, delta_of_output)

    # updating new weight
    #       3x1                        3x1
    weights_for_output_nurons += new_weight_output * lr

    # updating bias
    #  1x1                         sum(8x1) = 1x1
    bias_for_output_nurons += sum(delta_of_output) * lr

    # getting new weight for internal neurons.
    #     3x3              T(8x3) = 3x8               8x3
    new_weight_input = training_inputs.T.dot(delta_of_input_nurons)

    # updating weights for inputs
    #        3x3                       3x3
    weights_for_input_nurons += new_weight_input * lr

    # updating bias of inputs
    #      1x3                         sum(8x3) = 1x1
    bias_for_input_nurons += sum(delta_of_input_nurons) * lr


# giving input manually
user_input = array([1, 0, 0])
print("input given:\n", user_input)
weight_bias = dot(user_input, weights_for_input_nurons) + bias_for_input_nurons
output1 = sigmoid(weight_bias)
weight_bias1 = dot(output1, weights_for_output_nurons) + bias_for_output_nurons
output2 = sigmoid(weight_bias1)
print("predicted output: ", output2)


training input:
 [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
with 3 features and 8 sampels.
training output:
 [[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]]
weight matrix of 3 neurons:
 [[0.98197991 0.51940032 0.29419449]
 [0.0456775  0.14489941 0.34620746]
 [0.83743962 0.87503583 0.71021714]]
bias matrix of 3 neurons:
 [[0.77463982 0.25978565 0.57969931]]
weight matrix of output neuron:
 [[0.19991172]
 [0.81146442]
 [0.88321829]]
bias matrix of output neuron:
 [[0.7295808]]
input given:
 [1 0 0]
predicted output:  [[0.000666]]
